// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace WiFi_Indoor_Localization
{
    public partial class WiFi_IndoorLocalization
    {
        /// <summary>
        /// model input class for WiFi_IndoorLocalization.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"RSSI1")]
            public float RSSI1 { get; set; }

            [ColumnName(@"RSSI2")]
            public float RSSI2 { get; set; }

            [ColumnName(@"RSSI3")]
            public float RSSI3 { get; set; }

            [ColumnName(@"RSSI4")]
            public float RSSI4 { get; set; }

            [ColumnName(@"RSSI5")]
            public float RSSI5 { get; set; }

            [ColumnName(@"RSSI6")]
            public float RSSI6 { get; set; }

            [ColumnName(@"RSSI7")]
            public float RSSI7 { get; set; }

            [ColumnName(@"Room")]
            public float Room { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for WiFi_IndoorLocalization.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"RSSI1")]
            public float RSSI1 { get; set; }

            [ColumnName(@"RSSI2")]
            public float RSSI2 { get; set; }

            [ColumnName(@"RSSI3")]
            public float RSSI3 { get; set; }

            [ColumnName(@"RSSI4")]
            public float RSSI4 { get; set; }

            [ColumnName(@"RSSI5")]
            public float RSSI5 { get; set; }

            [ColumnName(@"RSSI6")]
            public float RSSI6 { get; set; }

            [ColumnName(@"RSSI7")]
            public float RSSI7 { get; set; }

            [ColumnName(@"Room")]
            public uint Room { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("WiFi_IndoorLocalization.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
